name: Build and Create MSI Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Adjust this version as required

    - name: Change to the directory containing the solution file
      run: cd src
      
    - name: Restore NuGet packages
      run: dotnet restore ChocolateyGui.sln # Adjust the solution file name if necessary
      
    - name: Build WiX MSI installer project
      run: |
        # Build the WiX project
        msbuild src/ChocolateyGui.Install/ChocolateyGui.Install.wixproj /t:Rebuild /p:Configuration=Release
        
      
    - name: Build WiX MSI installer project
      run: |
        # Build the WiX project
        msbuild ChocolateyGui.Install.wixproj /t:Rebuild /p:Configuration=Release
        
    - name: Publish MSI installer
      uses: actions/upload-artifact@v2
      with:
        name: ChocolateyGuiInstaller
        path: msi_drop/*.msi
