name: Build and Create MSI Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
     
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Adjust this version as required

    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: Change Directory | nuget restore
      shell: cmd
      run: |
        cd src
        nuget restore
        
    - name: Build Projects of the Solution | Create MSI installer
      shell: cmd
      run: |
        dir
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\msbuild.exe"
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\msbuild.exe" ChocolateyGui.Install\ChocolateyGui.Install.wixproj /t:Rebuild /p:Configuration=Debug
        
    - name: Publish MSI installer
      uses: actions/upload-artifact@v2
      with:
        name: ChocolateyGuiInstaller
        path: msi_drop/*.msi
