name: Build and Create MSI Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '4.8.x' # Adjust this version as required
        
    - name: Restore NuGet packages
      run: dotnet restore
      
    - name: Build WiX MSI installer project
      run: |
        # Change to the directory containing the WiX project file
        cd src/ChocolateyGui.Install

        # Build the WiX project
        msbuild ChocolateyGui.Install.wixproj /t:Rebuild /p:Configuration=Release
        
    - name: Publish MSI installer
      uses: actions/upload-artifact@v2
      with:
        name: ChocolateyGuiInstaller
        path: msi_drop/*.msi
