name: Build and Create MSI Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
     
    - name: Setup .NET environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Adjust this version as required

    - name: Checkout code
      uses: actions/checkout@v2
     
    - name: Change Directory | nuget restore | Build Projects of the Solution | Create MSI installer
      run: |
        cd src
        nuget restore
        dotnet build /t:Rebuild /p:Configuration=Debug
        dotnet build ChocolateyGui.Install\ChocolateyGui.Install.wixproj /t:Rebuild /p:Configuration=Debug
        
    - name: Publish MSI installer
      uses: actions/upload-artifact@v2
      with:
        name: ChocolateyGuiInstaller
        path: msi_drop/*.msi
